language: php

env:
  global:
    - setup=stable

matrix:
  include:
    - php: 7.0
      env:
        - testbench=3.4.x
        - phpunit=5.7.x
    - php: 7.0
      env:
        - testbench=3.5.x
        - phpunit=6.0.x
    - php: 7.1
      env:
        - testbench=3.5.x
        - phpunit=6.0.x
    - php: 7.1
      env:
        - testbench=3.6.x
        - phpunit=7.0.x
    - php: 7.1
      env:
        - testbench=3.6.x
        - phpunit=7.0.x
    - php: 7.1
      env:
        - testbench=3.7.x
        - phpunit=7.0.x
    - php: 7.2
      env:
        - testbench=3.5.x
        - phpunit=6.0.x
    - php: 7.2
      env:
        - testbench=3.6.x
        - phpunit=7.0.x
    - php: 7.2
      env:
        - testbench=3.6.x
        - phpunit=7.0.x
    - php: 7.2
      env:
        - testbench=3.7.x
        - phpunit=7.0.x

sudo: false

install:
  - composer require orchestra/testbench:${testbench} --dev --no-update
  - composer require phpunit/phpunit:${phpunit} --dev --no-update
  - if [[ $setup = 'stable' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-stable; fi
  - if [[ $setup = 'lowest' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-lowest --prefer-stable; fi

script:
  - vendor/bin/phpunit
